### ISSUE TITLE
Parsing file content to nf-gpt plugin

### ISSUE THREAD

**Issue by LeonHornich** [nextflow-io/nf-gpt#2]
Hello everyone,

i am currently trying to get the plugin to run for file data. That means i have a data file and want to parse the content to the plugin.
Since the plugin currently only accepts strings i need to do the following (at least that's where i am at right now):

1. Read or parse the file content into a string using nextflow
2. Use that string as input for the `gptPromptForText()` function

This is what i have so far:
```
nextflow.enable.dsl=2

include { gptPromptForText } from 'plugin/nf-gpt'

workflow {

    // define input
    def query = Channel
                .fromPath( 'data/data.bf' )
                .map { it -> it.text }

    query.view()

    // parse input to gpt prompt
    println gptPromptForText(query)
}
```

With this i am encountering the following error:
```
Launching `main.nf` [exotic_shirley] DSL2 - revision: 507e71f1b4

Missing process or function gptPromptForText([DataflowBroadcast around DataflowStream[?]]) -- Did you mean 'gptPromptForText' instead?

 -- Check script 'main.nf' at line: 17 or see '.nextflow.log' file for more details
```

Any thoughts why this might happen? Any solution to the problem or alternative approaches? I am happy for any help. 
Thanks in advance.

**Comment by pditommaso** [comment]
Much simpler, you can do 

```
    def data = file('data/data.bf').text
    // parse input to gpt prompt
    println gptPromptForText(data)
```

**Comment by LeonHornich** [comment]
I am trying to solve this specifically for a path channel. I have a process that generates a file. The process output is the path Channel of that file. The file content i now want to parse to the plugin. 

process:
```
process TEST_PROCESS {
    output:
    path 'query.txt', emit: query

    script:
    """
    #!/usr/bin/env python3

    test_string = "Tell me a joke"

    with open("query.txt", "w") as file:
        file.write(test_string)
    """
}
```

workflow:
```
nextflow.enable.dsl=2

include { gptPromptForText } from 'plugin/nf-gpt'
include { TEST_PROCESS     } from './modules/test_process'

workflow {
    TEST_PROCESS()
    def query = TEST_PROCESS.out.query
    
    println query
}
```

If i print the query Channel i get: `DataflowVariable(value=null)` , which i am assuming is the cause for my original message above.
I am still learning about nextflow so this is all very new and i am trying to grasp the concepts.

**Comment by pditommaso** [comment]
Then you can either invoke `gptPromptForText` in [a process](https://github.com/nextflow-io/nf-gpt/blob/master/examples/example2.nf#L13) or in map or [flatMap](https://github.com/nextflow-io/nf-gpt/blob/master/examples/example3.nf#L15) operator

**Comment by LeonHornich** [comment]
Thank you, i found a solution for my problem. I am not sure i was able to fully describe my issue here, but your suggestions helped.
